### PR TITLE
Allowing complex var names;

### PR DESCRIPTION
**Pull request by seangates**
Removing the else if block in order to allow complex var names on the left hand of the assignment.

### CODE REVIEW

**Comment by philidem** [comment]
Please fix the jshint error so that the build will pass. Also, jshint plugins/packages for your code editor are really helpful if you don't have one installed.

See https://travis-ci.org/raptorjs/marko/jobs/54955691

**Comment by seangates** [comment]
Funny, because I did the edits directly in Github. :-)

--
Sean Gates

**Comment by philidem** [comment]
Published marko@2.1.4
Thanks Sean!

**Comment by seangates** [comment]
You bet!

--
Sean Gates

**Pull request merged**
